#!/usr/bin/env bash

set -ex

docker build -t travis-debug tests

docker run \
  --name travis-debug \
  -v $(pwd):/home/travis/ansible-nvm \
  -dit \
  travis-debug \
  /sbin/init

sleep 1

docker exec -it travis-debug bash -l

docker stop travis-debug

docker rm travis-debug
